name: habit_tracker_app
description: "A scalable, production-ready offline-first Habit Tracker App built with Clean Architecture, Riverpod, sqflite, and go_router."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Cupertino icons for iOS style
  cupertino_icons: ^1.0.6

  # State Management
  flutter_riverpod: ^2.5.1

  # Local SQLite Database
  sqflite: ^2.3.0
  path: ^1.9.0

  # Routing
  go_router: ^14.0.1

  # Core Utilities
  uuid: ^4.3.3

  # Google Sign In Authentication
  google_sign_in: ^6.2.1

  # Firebase Suite & Network Monitor
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  connectivity_plus: ^6.0.3

  # Notifications
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.4
  flutter_timezone: ^3.0.1

  # File selection
  file_picker: ^11.0.0

  # Sharing/saving files
  share_plus: ^10.1.4

  # Path Provider
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter
  flutter_lints: ^3.0.0

  # Launcher Icons Generator
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Logo.png"
  adaptive_icon_background: "#111318" # Warna background gelap tema Dailio
  adaptive_icon_foreground: "assets/images/Logo.png"

flutter:
  uses-material-design: true

  # Untuk menambahkan aset seperti logo dan gambar
  assets:
    - assets/images/
