// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq1EMh6bRKNllkYlSHgLaf1lnozr646VU',
    appId: '1:152879355769:web:b1b878c4d056e5aa5101a8',
    messagingSenderId: '152879355769',
    projectId: 'dailio-habit-tracker',
    authDomain: 'dailio-habit-tracker.firebaseapp.com',
    storageBucket: 'dailio-habit-tracker.firebasestorage.app',
    measurementId: 'G-G2KR4KGCRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9sxPsSBLzANTnRUdLHO4ViW_9gHURyOQ',
    appId: '1:152879355769:android:34cf772e4fc99c8d5101a8',
    messagingSenderId: '152879355769',
    projectId: 'dailio-habit-tracker',
    storageBucket: 'dailio-habit-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT84hEe8L6sCU08MP0mWHr7qIVbPqhiRg',
    appId: '1:152879355769:ios:9321564a0385610b5101a8',
    messagingSenderId: '152879355769',
    projectId: 'dailio-habit-tracker',
    storageBucket: 'dailio-habit-tracker.firebasestorage.app',
    iosBundleId: 'com.habittracker.app.habitTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT84hEe8L6sCU08MP0mWHr7qIVbPqhiRg',
    appId: '1:152879355769:ios:9321564a0385610b5101a8',
    messagingSenderId: '152879355769',
    projectId: 'dailio-habit-tracker',
    storageBucket: 'dailio-habit-tracker.firebasestorage.app',
    iosBundleId: 'com.habittracker.app.habitTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq1EMh6bRKNllkYlSHgLaf1lnozr646VU',
    appId: '1:152879355769:web:1da74bfdc1e9d44a5101a8',
    messagingSenderId: '152879355769',
    projectId: 'dailio-habit-tracker',
    authDomain: 'dailio-habit-tracker.firebaseapp.com',
    storageBucket: 'dailio-habit-tracker.firebasestorage.app',
    measurementId: 'G-RYEGCY7YQY',
  );
}
